/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package klijent.forme.zicara;

import domen.OpstiDomenskiObjekat;
import domen.SkiCentar;
import domen.Zicara;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import klijent.kontroler.Kontroler;

/**
 *
 * @author UrosVesic
 */
public class KreirajZicaruForma extends javax.swing.JFrame {

    /**
     * Creates new form KreirajZicaruForma
     */
    Zicara zicara;

    public KreirajZicaruForma() {
        initComponents();
        prepare();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSifraZicare = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNazivZicare = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRadnoVreme = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtKapacitet = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbUfunkciji = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbSkiCentri = new javax.swing.JComboBox();
        btnKreiraj = new javax.swing.JButton();
        btnZapamti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sifra zicare: ");

        txtSifraZicare.setEditable(false);

        jLabel2.setText("Naziv zicare: ");

        jLabel3.setText("Radno vreme:");

        jLabel4.setText("Kapacitet:");

        jLabel5.setText("skijaša/sat");

        jLabel6.setText("U funkciji:");

        cmbUfunkciji.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DA", "NE" }));

        jLabel7.setText("Ski centar:");

        btnKreiraj.setText("Kreiraj");
        btnKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajActionPerformed(evt);
            }
        });

        btnZapamti.setText("Zapamti");
        btnZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZapamtiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRadnoVreme, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(txtNazivZicare)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtKapacitet)
                            .addComponent(cmbUfunkciji, 0, 57, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(cmbSkiCentri, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSifraZicare, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnKreiraj, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnZapamti, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSifraZicare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNazivZicare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRadnoVreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKapacitet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbUfunkciji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbSkiCentri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKreiraj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZapamti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajActionPerformed
        // TODO add your handling code here:
        zicara = new Zicara();

        try {
            Kontroler.getInstanca().kreirajZicaru(zicara);
            napuniGrafickiObjekat();
            JOptionPane.showMessageDialog(this, "Sistem je kreirao zicaru");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da kreira zicaru");
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnKreirajActionPerformed

    private void btnZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZapamtiActionPerformed
        // TODO add your handling code here:
        napuniDomenskiObjekat();
        
        try {
            Kontroler.getInstanca().zapamtiZicaru(zicara);
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio zicaru");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti zicaru");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnZapamtiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JButton btnZapamti;
    private javax.swing.JComboBox cmbSkiCentri;
    private javax.swing.JComboBox<String> cmbUfunkciji;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtKapacitet;
    private javax.swing.JTextField txtNazivZicare;
    private javax.swing.JTextField txtRadnoVreme;
    private javax.swing.JTextField txtSifraZicare;
    // End of variables declaration//GEN-END:variables

    private void prepare() {
        List<OpstiDomenskiObjekat> skiCentri = new ArrayList<>();
        try {
            skiCentri = Kontroler.getInstanca().ucitajListuSkiCentara(skiCentri);
            for (OpstiDomenskiObjekat skiCentar : skiCentri) {
                cmbSkiCentri.addItem((SkiCentar) skiCentar);
            }
        } catch (Exception ex) {
            Logger.getLogger(KreirajZicaruForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void napuniGrafickiObjekat() {
        txtSifraZicare.setText(String.valueOf(zicara.getSifraZicare()));
        txtNazivZicare.setText(zicara.getNazivZicare());
        txtRadnoVreme.setText(zicara.getRadnoVreme());
        txtKapacitet.setText(String.valueOf(zicara.getKapacitet()));
    }

    private void napuniDomenskiObjekat() {
        zicara.setNazivZicare(txtNazivZicare.getText());
        zicara.setRadnoVreme(txtRadnoVreme.getText());
        zicara.setKapacitet(Integer.parseInt(txtKapacitet.getText()));
        if (cmbUfunkciji.getSelectedItem().equals("DA")) {
            zicara.setUFunkciji(true);
        } else {
            zicara.setUFunkciji(false);
        }
        zicara.setSkiCentar((SkiCentar) cmbSkiCentri.getSelectedItem());
    }
}
